/**
 * Writes `dist/_headers` after a build, including a Content-Security-Policy
 * whose script and style allowances are SHA-256 hashes of the inline blocks
 * Astro actually emitted.
 *
 * Runs automatically as part of `npm run build`.
 *
 * Hashes rather than 'unsafe-inline': the site has two inline scripts it cannot
 * do without — the pre-paint theme resolver and the JS-available flag — and
 * allowing all inline script to keep them would give away most of what a CSP is
 * for. A static host cannot use nonces, since the HTML is not generated per
 * request, so hashes are the remaining option.
 */
import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const dist = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist');

const sha256 = (content) => `'sha256-${createHash('sha256').update(content, 'utf8').digest('base64')}'`;

async function htmlFiles(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await htmlFiles(path)));
    else if (entry.name.endsWith('.html')) found.push(path);
  }
  return found;
}

const scriptHashes = new Set();
const styleHashes = new Set();
// Only opened up when the booking feature is actually switched on, so an
// unconfigured site keeps the tighter policy.
let embedsBooking = false;
// Same idea for the instant site audit: only widen connect-src when the tool is
// actually on the page, which it only is when a PageSpeed key was configured.
let callsPageSpeed = false;
// And again for Cloudflare Web Analytics: the beacon is only in the HTML when a
// token was configured, so an unmeasured build never advertises the origin.
let sendsAnalytics = false;

// Matches an inline <script> (no src) or <style>, capturing its attributes and body.
const inlineBlock = /<(script|style)([^>]*)>([\s\S]*?)<\/\1>/gi;

for (const file of await htmlFiles(dist)) {
  const html = await readFile(file, 'utf8');
  if (html.includes('href="https://cal.com/')) embedsBooking = true;
  if (html.includes('data-psi-endpoint="https://www.googleapis.com/')) callsPageSpeed = true;
  if (html.includes('src="https://static.cloudflareinsights.com/beacon.min.js"')) sendsAnalytics = true;

  for (const [, tag, attrs, body] of html.matchAll(inlineBlock)) {
    if (/\ssrc\s*=/i.test(attrs)) continue; // external, covered by 'self'
    if (!body.trim()) continue;

    if (tag.toLowerCase() === 'style') {
      styleHashes.add(sha256(body));
      continue;
    }

    // Data blocks such as application/ld+json are never executed, so CSP
    // does not gate them and they need no hash.
    const type = attrs.match(/\stype\s*=\s*["']?([^"'\s>]+)/i)?.[1]?.toLowerCase();
    if (type && type !== 'module' && !/javascript|ecmascript/.test(type)) continue;

    scriptHashes.add(sha256(body));
  }
}

// cal.com is framed directly rather than through their embed script, so this
// needs a frame-src and nothing more — no third-party script, no unsafe-inline.
const bookingOrigins = embedsBooking ? ' https://cal.com https://app.cal.com' : '';
// The audit runs in the visitor's browser, so the call to Google goes out from
// the page rather than from a server of ours.
const auditOrigin = callsPageSpeed ? ' https://www.googleapis.com' : '';
// The beacon is served from one host and reports to another, so switching
// analytics on costs two allowances, not one.
const beaconScript = sendsAnalytics ? ' https://static.cloudflareinsights.com' : '';
const beaconTarget = sendsAnalytics ? ' https://cloudflareinsights.com' : '';

const csp = [
  "default-src 'self'",
  `script-src 'self'${beaconScript} ${[...scriptHashes].sort().join(' ')}`,
  `style-src 'self' ${[...styleHashes].sort().join(' ')}`,
  "img-src 'self' data:",
  "font-src 'self'",
  // The contact form posts here when a Web3Forms key is configured.
  `connect-src 'self' https://api.web3forms.com${auditOrigin}${beaconTarget}`,
  "form-action 'self' https://api.web3forms.com",
  `frame-src 'none'${bookingOrigins}`.replace("'none' ", ''),
  "base-uri 'none'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

// Listed one by one rather than globbed: `/*.png` also matches `/og/home.png`,
// and since the last matching rule in a _headers file wins, the share images
// quietly picked up the icon cache lifetime. Caught by the test, not by eye.
const staticAssets = (await readdir(dist, { withFileTypes: true }))
  .filter((entry) => entry.isFile() && /\.(png|svg|webmanifest)$/.test(entry.name))
  .map((entry) => entry.name)
  .sort();

const staticAssetRules = staticAssets
  .map((name) => `/${name}\n  Cache-Control: public, max-age=86400`)
  .join('\n');

const headers = `# Generated by scripts/build-headers.mjs — do not edit by hand.
# The CSP hashes are derived from the inline blocks in the built HTML, so they
# change whenever those scripts or the font CSS change.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains

# Everything under /_astro/ carries a content hash in its filename, so it can
# be cached forever — a change produces a new filename.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# Share images are regenerated on every build but keep the same file names, so
# they cannot be cached forever — an hour is enough for the crawlers that fetch
# them in bursts, and short enough that a redesign shows up the same day.
/og/*
  Cache-Control: public, max-age=3600

# Icons and the manifest change rarely and are not content-hashed.
${staticAssetRules}

# This file exists so you can check which commit is live. A cached copy of it
# would answer the one question it was built to answer, wrongly.
/version.txt
  Cache-Control: no-store
`;

await writeFile(join(dist, '_headers'), headers);
console.log(
  `_headers written: ${scriptHashes.size} script hash(es), ${styleHashes.size} style hash(es)` +
    `${embedsBooking ? ', booking frame allowed' : ''}` +
    `${sendsAnalytics ? ', analytics beacon allowed' : ''}`,
);
