/**
 * Writes `dist/_headers` after a build, including a Content-Security-Policy
 * whose script and style allowances are SHA-256 hashes of the inline blocks
 * Astro actually emitted.
 *
 * Runs automatically as part of `npm run build`.
 *
 * Hashes rather than 'unsafe-inline': the site has two inline scripts it cannot
 * do without — the pre-paint theme resolver and the JS-available flag — and
 * allowing all inline script to keep them would give away most of what a CSP is
 * for. A static host cannot use nonces, since the HTML is not generated per
 * request, so hashes are the remaining option.
 */
import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const dist = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist');

const sha256 = (content) => `'sha256-${createHash('sha256').update(content, 'utf8').digest('base64')}'`;

async function htmlFiles(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await htmlFiles(path)));
    else if (entry.name.endsWith('.html')) found.push(path);
  }
  return found;
}

const scriptHashes = new Set();
const styleHashes = new Set();
// Only opened up when the booking feature is actually switched on, so an
// unconfigured site keeps the tighter policy.
let embedsBooking = false;

// Matches an inline <script> (no src) or <style>, capturing its attributes and body.
const inlineBlock = /<(script|style)([^>]*)>([\s\S]*?)<\/\1>/gi;

for (const file of await htmlFiles(dist)) {
  const html = await readFile(file, 'utf8');
  if (html.includes('href="https://cal.com/')) embedsBooking = true;

  for (const [, tag, attrs, body] of html.matchAll(inlineBlock)) {
    if (/\ssrc\s*=/i.test(attrs)) continue; // external, covered by 'self'
    if (!body.trim()) continue;

    if (tag.toLowerCase() === 'style') {
      styleHashes.add(sha256(body));
      continue;
    }

    // Data blocks such as application/ld+json are never executed, so CSP
    // does not gate them and they need no hash.
    const type = attrs.match(/\stype\s*=\s*["']?([^"'\s>]+)/i)?.[1]?.toLowerCase();
    if (type && type !== 'module' && !/javascript|ecmascript/.test(type)) continue;

    scriptHashes.add(sha256(body));
  }
}

// cal.com is framed directly rather than through their embed script, so this
// needs a frame-src and nothing more — no third-party script, no unsafe-inline.
const bookingOrigins = embedsBooking ? ' https://cal.com https://app.cal.com' : '';

const csp = [
  "default-src 'self'",
  `script-src 'self' ${[...scriptHashes].sort().join(' ')}`,
  `style-src 'self' ${[...styleHashes].sort().join(' ')}`,
  "img-src 'self' data:",
  "font-src 'self'",
  // The contact form posts here when a Web3Forms key is configured.
  "connect-src 'self' https://api.web3forms.com",
  "form-action 'self' https://api.web3forms.com",
  `frame-src 'none'${bookingOrigins}`.replace("'none' ", ''),
  "base-uri 'none'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

const headers = `# Generated by scripts/build-headers.mjs — do not edit by hand.
# The CSP hashes are derived from the inline blocks in the built HTML, so they
# change whenever those scripts or the font CSS change.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin

# Everything under /_astro/ carries a content hash in its filename, so it can
# be cached forever — a change produces a new filename.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable
`;

await writeFile(join(dist, '_headers'), headers);
console.log(
  `_headers written: ${scriptHashes.size} script hash(es), ${styleHashes.size} style hash(es)` +
    `${embedsBooking ? ', booking frame allowed' : ''}`,
);
